Commandline: apt-get install smbclient
Commandline: apt-get install arping
Commandline: apt-get install xorriso
Commandline: apt-get install strace
Commandline: apt-get install bc
Commandline: apt-get remove curl
Commandline: apt-get install uuid
Commandline: apt-get install tcpdump
Commandline: apt-get install net-tools
Commandline: apt-get install git
Commandline: apt-get install build-essential
Commandline: apt-get install tmux
Commandline: apt-get install gdb
Commandline: apt-get install subversion
Commandline: apt-get install jq
Commandline: apt-get install silversearcher-ag
Commandline: apt-get install samba
Commandline: apt-get install sshpass
Commandline: apt-get install zip
Commandline: apt-get install autoconf
Commandline: apt-get install pkg-config
Commandline: apt-get install python-pip
Commandline: apt-get install cmake
Commandline: apt-get install graphviz
Commandline: apt-get install openjdk-8-jre
Commandline: apt-get install apache2
Commandline: apt-get install pandoc
Commandline: apt-get install dialog

Commandline: apt-get install memcached
