" common setting {{{
let mapleader = ';'
set nocompatible
set ruler
set shiftwidth=4
set softtabstop=4
set tabstop=4

set ignorecase smartcase
set incsearch
set hlsearch
set noerrorbells
set showmatch
set smartindent
set number
set encoding=utf-8
" }}}

" for vimrc edit or source {{{
nnoremap <Leader>ev :vsplit $MYVIMRC<cr>
nnoremap <Leader>sv :source $MYVIMRC<cr>
" }}}

" vim script code fold {{{
augroup filetype_vim
	autocmd!
	autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}

" vim plugin list {{{
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
" plugin manager
Plug 'junegunn/vim-plug'

" fuzzy finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" highlight the keywords
Plug 'lfv89/vim-interestingwords'

" comment/uncomment tool
Plug 'scrooloose/nerdcommenter'

" the vim start screen
Plug 'mhinz/vim-startify'

" format code
Plug 'Chiel92/vim-autoformat'

" file template when create new file
Plug 'aperezdc/vim-template'

" quoting/parentheses made simple
Plug 'tpope/vim-surround'

" show diff with style
Plug 'mhinz/vim-signify'

" show tags in a window
Plug 'majutsushi/tagbar'

" file system explorer
Plug 'scrooloose/nerdtree'

" the ultimate snippet solution for Vim
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" the code search 
Plug 'mileszs/ack.vim'

" insert or delete brackets, parens, quotes in pair 
Plug 'jiangmiao/auto-pairs'

" a git wrapper
Plug 'tpope/vim-fugitive'

" find and replace plugin
Plug 'brooth/far.vim'

" asynchronous linting/fixing
Plug 'w0rp/ale'

" sort python imports
Plug 'fisadev/vim-isort'

" a simple function navigator
Plug 'tacahiroy/ctrlp-funky'

" flake8 for vim
Plug 'nvie/vim-flake8'

" the code complete
Plug 'Valloric/YouCompleteMe'


call plug#end()
" }}}

" fzf setting {{{
nnoremap <c-p> :FZF<CR>
" }}}

" tagbar setting {{{
nnoremap <F8> :TagbarToggle<CR>
" }}}

" UltiSnips setting {{{
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
" }}}

" ack setting {{{
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>
" }}}

