require('options')
require('colorscheme')

require('keymaps')

-- for plugins
require('plugins/packer')
require('plugins/nvim-cmp')
require('plugins/telescope-fzf-native')
require('plugins/telescope')
require('plugins/nvim-web-devicons')
require('plugins/nvim-tree')
require('plugins/deadcolumns')
require('plugins/nvim-hardline')
require('plugins/barbar')
require('plugins/gitsigns')
require('plugins/nvim-spectre')
require('plugins/interestingwords')
require('plugins/aerial')
require('plugins/nvim-treesitter-textobjects')
require('plugins/nvim-surround')
require('plugins/diffview')
require('plugins/hop')
require('plugins/neoscroll')
require('plugins/nvim-lastplace')
require('plugins/nvim-autopairs')
require('plugins/nvim-ts-autotag')
require('plugins/comment')
require('plugins/neogen')
require('plugins/nvim-lspconfig')
